<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="glass-panel">
      <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 class="panel-title">每日精选配置</h2>
          <p class="panel-sub">按日期管理精选资源 · 搜索添加资源 · 配置自动精选</p>
        </div>
        <div class="flex gap-2">
          <button class="btn-soft" @click="showAutoConfig = true">自动精选设置</button>
        </div>
      </div>
    </div>

    <!-- Date Picker -->
    <div class="glass-panel flex flex-wrap items-center gap-3">
      <span class="text-sm text-[var(--text-sub)]">选择日期：</span>
      <input v-model="selectedDate" type="date" class="input w-44" @change="loadPicks" />
      <div class="flex gap-1">
        <button class="btn-soft text-xs px-3" @click="shiftDate(-1)">前一天</button>
        <button class="btn-soft text-xs px-3" @click="shiftDate(1)">后一天</button>
      </div>
      <button class="btn-soft text-xs" @click="selectedDate = todayStr(); loadPicks()">今天</button>
      <span v-if="picksData?.autoGenerated" class="px-2 py-0.5 rounded text-xs bg-blue-500/10 text-blue-500">自动生成</span>
    </div>

    <!-- Current Picks -->
    <div class="glass-panel">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-sm font-semibold text-[var(--text-main)]">
          {{ selectedDate }} 精选资源
          <span v-if="picksData?.resources?.length" class="text-[var(--text-sub)] font-normal">({{ picksData.resources.length }}项)</span>
        </h3>
        <button class="btn-soft text-sm gap-1" @click="showResourcePicker = true">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
          添加资源
        </button>
      </div>

      <div v-if="picksLoading" class="animate-pulse py-8 text-center text-[var(--text-sub)]">加载中...</div>
      <div v-else-if="!picksData?.resources?.length" class="py-12 text-center">
        <p class="text-[var(--text-sub)]">该日期暂无精选配置</p>
        <p class="text-xs text-[var(--text-sub)] mt-1">点击"添加资源"开始配置</p>
      </div>
      <div v-else class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-3">
        <div
          v-for="item in picksData.resources"
          :key="item._id"
          class="group relative bg-[var(--bg-body)] rounded-xl overflow-hidden border border-[var(--border-color)] hover:shadow-md transition-all"
        >
          <button
            class="absolute top-1 right-1 z-10 w-6 h-6 rounded-full bg-red-500/90 text-white flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
            @click="removeResource(item._id)"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
          <div class="aspect-[3/4] bg-[var(--border-color)] overflow-hidden">
            <img v-if="item.coverUrl" :src="item.coverUrl" class="w-full h-full object-cover" />
          </div>
          <div class="p-2">
            <p class="text-xs font-medium truncate">{{ item.title || '无标题' }}</p>
            <span class="text-[10px] px-1.5 py-0.5 rounded mt-1 inline-block" :style="item.type === 'avatar' ? { background: 'rgba(168,85,247,0.1)', color: '#a855f7' } : { background: 'rgba(59,130,246,0.1)', color: '#3b82f6' }">
              {{ item.type === 'avatar' ? '头像' : '壁纸' }}
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Resource Picker Modal -->
    <div v-if="showResourcePicker" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" @click="showResourcePicker = false">
      <div class="bg-[var(--bg-card)] rounded-2xl shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col border border-[var(--border-color)]" @click.stop>
        <div class="px-6 py-4 border-b border-[var(--border-color)] flex items-center justify-between shrink-0">
          <h3 class="text-lg font-bold text-[var(--text-main)]">添加资源到精选</h3>
          <button class="text-[var(--text-sub)] hover:text-[var(--text-main)] p-1" @click="showResourcePicker = false">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>

        <div class="px-6 py-3 border-b border-[var(--border-color)] shrink-0">
          <div class="flex gap-2">
            <input v-model="searchKeyword" placeholder="搜索资源标题/标签" class="input flex-1" @keyup.enter="searchResources" />
            <select v-model="searchType" class="select w-28">
              <option value="all">全部</option>
              <option value="avatar">头像</option>
              <option value="wallpaper">壁纸</option>
            </select>
            <button class="btn-soft" @click="searchResources">搜索</button>
          </div>
        </div>

        <div class="flex-1 overflow-y-auto p-4">
          <div v-if="searchLoading" class="py-8 text-center text-[var(--text-sub)]">搜索中...</div>
          <div v-else-if="searchResults.length === 0" class="py-8 text-center text-[var(--text-sub)]">输入关键词搜索资源</div>
          <div v-else class="grid grid-cols-2 sm:grid-cols-3 gap-3">
            <div
              v-for="item in searchResults"
              :key="item._id"
              class="relative bg-[var(--bg-body)] rounded-xl overflow-hidden border border-[var(--border-color)] cursor-pointer hover:shadow-md transition-all"
              :class="{ 'ring-2 ring-[var(--primary)] opacity-60': isAlreadyPicked(item._id) }"
              @click="!isAlreadyPicked(item._id) && addToPicks(item._id)"
            >
              <div class="aspect-[3/4] bg-[var(--border-color)] overflow-hidden">
                <img v-if="item.coverUrl" :src="item.coverUrl" class="w-full h-full object-cover" />
              </div>
              <div class="p-2">
                <p class="text-xs font-medium truncate">{{ item.title || '无标题' }}</p>
              </div>
              <div v-if="isAlreadyPicked(item._id)" class="absolute inset-0 flex items-center justify-center">
                <span class="px-3 py-1 bg-[var(--primary)] text-white text-xs rounded-full">已添加</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Auto Config Modal -->
    <div v-if="showAutoConfig" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" @click="showAutoConfig = false">
      <div class="bg-[var(--bg-card)] rounded-2xl shadow-2xl w-full max-w-sm border border-[var(--border-color)]" @click.stop>
        <div class="px-6 py-4 border-b border-[var(--border-color)]">
          <h3 class="text-lg font-bold text-[var(--text-main)]">自动精选设置</h3>
        </div>
        <div class="p-6 space-y-4">
          <div class="flex items-center gap-3">
            <button
              class="w-11 h-6 rounded-full relative transition-all shrink-0"
              :style="autoConfig.enabled ? { background: 'var(--primary)' } : { background: '#d1d5db' }"
              @click="autoConfig.enabled = !autoConfig.enabled"
            >
              <span class="absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full transition-transform shadow-sm" :style="{ transform: autoConfig.enabled ? 'translateX(20px)' : '' }"></span>
            </button>
            <div>
              <p class="text-sm font-medium text-[var(--text-main)]">启用自动精选</p>
              <p class="text-xs text-[var(--text-sub)]">关闭后将不再自动生成每日精选</p>
            </div>
          </div>
          <div>
            <label class="text-sm font-medium text-[var(--text-main)] block mb-1">最少资源数</label>
            <input v-model.number="autoConfig.minCount" type="number" min="1" class="input w-full" />
          </div>
          <div>
            <label class="text-sm font-medium text-[var(--text-main)] block mb-1">最多资源数</label>
            <input v-model.number="autoConfig.maxCount" type="number" min="1" class="input w-full" />
          </div>
        </div>
        <div class="px-6 py-4 border-t border-[var(--border-color)] flex justify-end gap-3">
          <button class="px-4 py-2 text-sm text-[var(--text-sub)]" @click="showAutoConfig = false">取消</button>
          <button class="btn-primary" :disabled="savingAutoConfig" @click="saveAutoConfig">
            {{ savingAutoConfig ? '保存中...' : '保存' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useMessage } from 'naive-ui'
import { callCloudFunction } from '../utils/cloudbase'

const message = useMessage()

function todayStr() {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}

const selectedDate = ref(todayStr())
const picksData = ref<any>(null)
const picksLoading = ref(false)

function shiftDate(days: number) {
  const d = new Date(selectedDate.value)
  d.setDate(d.getDate() + days)
  selectedDate.value = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
  loadPicks()
}

async function loadPicks() {
  picksLoading.value = true
  try {
    const res = await callCloudFunction('manageDailyPicks', {
      action: 'getPicksByDate',
      date: selectedDate.value
    })
    picksData.value = res?.data || null
  } catch (_e: any) {
    message.error('加载失败')
  } finally {
    picksLoading.value = false
  }
}

async function removeResource(resourceId: string) {
  try {
    await callCloudFunction('manageDailyPicks', {
      action: 'removePick',
      date: selectedDate.value,
      resourceId
    })
    message.success('已移除')
    loadPicks()
  } catch (_e: any) {
    message.error('移除失败')
  }
}

// ====== Resource Picker ======
const showResourcePicker = ref(false)
const searchKeyword = ref('')
const searchType = ref('all')
const searchResults = ref<any[]>([])
const searchLoading = ref(false)

async function searchResources() {
  if (!searchKeyword.value.trim()) return
  searchLoading.value = true
  try {
    const res = await callCloudFunction('getResources', {
      keyword: searchKeyword.value.trim(),
      type: searchType.value === 'all' ? undefined : searchType.value,
      status: 'published',
      page: 1,
      limit: 30
    })
    searchResults.value = res?.data || []
  } catch (_e: any) {
    message.error('搜索失败')
  } finally {
    searchLoading.value = false
  }
}

function isAlreadyPicked(id: string) {
  return (picksData.value?.resources || []).some((r: any) => r._id === id)
}

async function addToPicks(resourceId: string) {
  const currentIds = (picksData.value?.resources || []).map((r: any) => r._id)
  const newIds = [...currentIds, resourceId]
  try {
    await callCloudFunction('manageDailyPicks', {
      action: 'setPicks',
      date: selectedDate.value,
      resourceIds: newIds
    })
    message.success('已添加')
    loadPicks()
  } catch (_e: any) {
    message.error('添加失败')
  }
}

// ====== Auto Config ======
const showAutoConfig = ref(false)
const autoConfig = reactive({ enabled: true, minCount: 6, maxCount: 12 })
const savingAutoConfig = ref(false)

async function loadAutoConfig() {
  try {
    const res = await callCloudFunction('manageDailyPicks', { action: 'getAutoConfig' })
    if (res?.data) {
      Object.assign(autoConfig, res.data)
    }
  } catch (e) {
    console.error(e)
  }
}

async function saveAutoConfig() {
  savingAutoConfig.value = true
  try {
    await callCloudFunction('manageDailyPicks', { action: 'updateAutoConfig', data: { ...autoConfig } })
    message.success('设置已保存')
    showAutoConfig.value = false
  } catch (_e: any) {
    message.error('保存失败')
  } finally {
    savingAutoConfig.value = false
  }
}

onMounted(() => {
  loadPicks()
  loadAutoConfig()
})
</script>
