<template>
  <view class="page-container daily-picks-page" style="padding-bottom: calc(180rpx + env(safe-area-inset-bottom));">
    <!-- 日期选择 -->
    <view class="date-bar">
      <text class="date-bar__label">精选日期</text>
      <picker mode="date" :value="selectedDate" @change="onDateChange">
        <view class="date-bar__picker">
          <mc-icon :path="icons.calendar" color="#07C160" :size="30" />
          <text class="date-bar__value">{{ selectedDate }}</text>
        </view>
      </picker>
      <view class="badge badge--green" v-if="autoGenerated">自动生成</view>
    </view>

    <!-- 自动精选配置 -->
    <view class="card">
      <view class="card__head">
        <text class="card__title">自动精选</text>
        <view class="toggle" :class="{ 'toggle--on': autoConfig.enabled }" @tap="onToggleAuto">
          <view class="toggle__knob" />
        </view>
      </view>
      <view class="auto-row">
        <text class="auto-label">最少数量</text>
        <input class="auto-input" type="number" :value="autoConfig.minCount" @input="onAutoMin" />
      </view>
      <view class="auto-row">
        <text class="auto-label">最多数量</text>
        <input class="auto-input" type="number" :value="autoConfig.maxCount" @input="onAutoMax" />
      </view>
      <mc-btn type="default" size="sm" @click="saveAutoConfig">保存自动配置</mc-btn>
    </view>

    <!-- 当日精选列表 -->
    <view class="card">
      <view class="card__title">当日精选（{{ picks.length }}）</view>
      <block v-if="loading">
        <view class="skeleton" style="height:120rpx;margin-bottom:16rpx" v-for="n in 3" :key="n" />
      </block>
      <block v-else-if="picks.length > 0">
        <view class="pick-item" v-for="p in picks" :key="p._id">
          <view class="pick-item__cover" v-if="isHttp(p.coverUrl)" :style="{ backgroundImage: 'url(' + p.coverUrl + ')' }" />
          <view class="pick-item__cover pick-item__cover--ph" v-else>
            <text>{{ typeLabel(p.type) }}</text>
          </view>
          <view class="pick-item__info">
            <text class="pick-item__title text-ellipsis">{{ p.title || '未命名' }}</text>
            <view class="badge badge--purple">{{ typeLabel(p.type) }}</view>
          </view>
          <view class="pick-item__del" @tap="onRemovePick(p)">
            <mc-icon :path="icons.trash" color="#FA5151" :size="30" />
          </view>
        </view>
      </block>
      <mc-empty v-else text="当日暂无精选，添加资源 ID 生成" />
    </view>

    <!-- 添加资源 -->
    <view class="card">
      <view class="card__title">添加资源</view>
      <textarea class="add-input" :value="newIds" @input="onNewIds" placeholder="粘贴资源 ID，多个用逗号 / 空格 / 换行分隔" :adjust-position="true" cursor-spacing="20" />
      <mc-btn type="primary" :loading="saving" :disabled="saving" @click="onSavePicks">保存为当日精选</mc-btn>
    </view>
  </view>
</template>

<script>
import api from '../../utils/api'
import { toast, showLoading, hideLoading, confirm } from '../../utils/format'

const TYPE_LABEL = { wallpaper: '壁纸', avatar: '头像', all: '全部' }
function typeLabel(t) { return TYPE_LABEL[t] || (t || '资源') }

export default {
  data() {
    return {
      selectedDate: '',
      picks: [],
      autoGenerated: false,
      autoConfig: { enabled: true, minCount: 6, maxCount: 12 },
      newIds: '',
      loading: false,
      saving: false,
      icons: {
        calendar: '<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',
        trash: '<polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
      },
    }
  },

  onLoad() {
    this.selectedDate = this.today()
    this.loadPicks()
    this.loadAutoConfig()
  },

  methods: {
    today() {
      const d = new Date()
      const p = (n) => (n < 10 ? '0' + n : '' + n)
      return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate())
    },
    isHttp(u) {
      return typeof u === 'string' && (u.indexOf('http://') === 0 || u.indexOf('https://') === 0)
    },
    typeLabel,

    async loadPicks() {
      this.loading = true
      try {
        const data = await api.getDailyPicksByDate(this.selectedDate)
        this.picks = data.resources || []
        this.autoGenerated = !!data.autoGenerated
      } catch (err) {
        console.error('[daily-picks] 加载失败', err)
        this.picks = []
        toast('加载失败')
      } finally {
        this.loading = false
      }
    },

    async loadAutoConfig() {
      try {
        const d = await api.getDailyPicksAutoConfig()
        if (d) this.autoConfig = { enabled: d.enabled !== false, minCount: d.minCount || 6, maxCount: d.maxCount || 12 }
      } catch (err) {
        console.error('[daily-picks] 自动配置加载失败', err)
      }
    },

    onDateChange(e) {
      this.selectedDate = e.detail.value
      this.loadPicks()
    },

    onToggleAuto() {
      this.autoConfig.enabled = !this.autoConfig.enabled
    },
    onAutoMin(e) { this.autoConfig.minCount = Number(e.detail.value) || 0 },
    onAutoMax(e) { this.autoConfig.maxCount = Number(e.detail.value) || 0 },

    async saveAutoConfig() {
      showLoading('保存中…')
      try {
        await api.updateDailyPicksAutoConfig(this.autoConfig)
        hideLoading()
        toast('已保存', 'success')
      } catch (err) {
        hideLoading()
        console.error('[daily-picks] 保存自动配置失败', err)
        toast('保存失败')
      }
    },

    onNewIds(e) { this.newIds = e.detail.value },

    parseIds() {
      return this.newIds.split(/[\s,，]+/).map((s) => s.trim()).filter(Boolean)
    },

    async onSavePicks() {
      const ids = this.parseIds()
      if (ids.length === 0) { toast('请输入资源 ID'); return }
      const existing = this.picks.map((p) => p._id).filter(Boolean)
      const merged = existing.concat(ids.filter((id) => existing.indexOf(id) < 0))
      this.saving = true
      showLoading('保存中…')
      try {
        await api.setDailyPicks(this.selectedDate, merged)
        hideLoading()
        this.saving = false
        this.newIds = ''
        toast('已保存', 'success')
        this.loadPicks()
      } catch (err) {
        hideLoading()
        this.saving = false
        console.error('[daily-picks] 保存失败', err)
        toast('保存失败')
      }
    },

    async onRemovePick(p) {
      const ok = await confirm('从当日精选移除「' + (p.title || '该资源') + '」？')
      if (!ok) return
      showLoading('移除中…')
      try {
        await api.removeDailyPick(this.selectedDate, p._id)
        hideLoading()
        toast('已移除', 'success')
        this.loadPicks()
      } catch (err) {
        hideLoading()
        console.error('[daily-picks] 移除失败', err)
        toast('移除失败')
      }
    },
  },
}
</script>

<style lang="scss" scoped>
.daily-picks-page {
  // padding 由内联 style 控制
}

.date-bar {
  display: flex;
  align-items: center;
  gap: 16rpx;
  background: var(--bg-card, #FFFFFF);
  border-radius: var(--r-lg, 28rpx);
  padding: 24rpx 28rpx;
  margin-bottom: 24rpx;
  box-shadow: var(--shadow-card, 0 4rpx 16rpx rgba(0, 0, 0, 0.04));
}
.date-bar__label {
  font-size: 28rpx;
  color: var(--text-secondary, #8C8CA1);
}
.date-bar__picker {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-left: auto;
  background: var(--bg, #F5F6F8);
  border-radius: var(--r-pill, 999rpx);
  padding: 12rpx 28rpx;
}
.date-bar__value {
  font-size: 28rpx;
  font-weight: 600;
  color: var(--text-primary, #1A1A2E);
}

.card {
  background: var(--bg-card, #FFFFFF);
  border-radius: var(--r-lg, 28rpx);
  padding: 28rpx 32rpx;
  margin-bottom: 24rpx;
  box-shadow: var(--shadow-card, 0 4rpx 16rpx rgba(0, 0, 0, 0.04));
}
.card__head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 20rpx;
}
.card__title {
  font-size: 28rpx;
  font-weight: 600;
  color: var(--text-primary, #1A1A2E);
  margin-bottom: 20rpx;
}
.card__head .card__title {
  margin-bottom: 0;
}

.auto-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 20rpx;
}
.auto-label {
  font-size: 26rpx;
  color: var(--text-secondary, #8C8CA1);
}
.auto-input {
  width: 160rpx;
  height: 72rpx;
  text-align: center;
  background: var(--bg, #F5F6F8);
  border: 1rpx solid var(--border, #EBEBF0);
  border-radius: var(--r-sm, 14rpx);
  font-size: 28rpx;
  color: var(--text-primary, #1A1A2E);
}

.toggle {
  width: 88rpx;
  height: 48rpx;
  border-radius: 24rpx;
  background: var(--tx3, #B8B8C8);
  position: relative;
  transition: background 0.2s;
  flex-shrink: 0;
}
.toggle--on {
  background: var(--pri, #07C160);
}
.toggle__knob {
  position: absolute;
  top: 4rpx;
  left: 4rpx;
  width: 40rpx;
  height: 40rpx;
  border-radius: 50%;
  background: #fff;
  transition: transform 0.2s;
}
.toggle--on .toggle__knob {
  transform: translateX(40rpx);
}

.pick-item {
  display: flex;
  align-items: center;
  gap: 20rpx;
  padding: 16rpx 0;
  border-bottom: 1rpx solid var(--divider, #F0F0F5);
}
.pick-item:last-child {
  border-bottom: none;
}
.pick-item__cover {
  width: 96rpx;
  height: 96rpx;
  border-radius: var(--r-sm, 14rpx);
  background-size: cover;
  background-position: center;
  background-color: var(--bg, #F5F6F8);
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}
.pick-item__cover--ph {
  font-size: 22rpx;
  color: var(--text-tertiary, #B8B8C8);
}
.pick-item__info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 10rpx;
  align-items: flex-start;
}
.pick-item__title {
  font-size: 28rpx;
  color: var(--text-primary, #1A1A2E);
  max-width: 100%;
}
.pick-item__del {
  width: 64rpx;
  height: 64rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.add-input {
  width: 100%;
  height: 160rpx;
  background: var(--bg, #F5F6F8);
  border: 1rpx solid var(--border, #EBEBF0);
  border-radius: var(--r-sm, 14rpx);
  padding: 20rpx 24rpx;
  font-size: 26rpx;
  color: var(--text-primary, #1A1A2E);
  box-sizing: border-box;
  margin-bottom: 20rpx;
}

.badge {
  display: inline-block;
  padding: 4rpx 16rpx;
  border-radius: var(--r-pill, 999rpx);
  font-size: 20rpx;
  font-weight: 500;
}
.badge--green {
  background: var(--pri-l, #E8F8EE);
  color: var(--pri-d, #06AD56);
}
.badge--purple {
  background: rgba(124, 92, 252, 0.12);
  color: #7C5CFC;
}
</style>
