const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()
const _ = db.command

const { withAdmin } = require('./withAdmin.js')

exports.main = withAdmin(async (event, context, admin) => {
  const { action } = event

  try {
    switch (action) {
      case 'getPicksByDate':
        return await getPicksByDate(event)
      case 'setPicks':
        return await setPicks(event, admin)
      case 'removePick':
        return await removePick(event)
      case 'getPicksRange':
        return await getPicksRange(event)
      case 'getAutoConfig':
        return await getAutoConfig()
      case 'updateAutoConfig':
        return await updateAutoConfig(event)
      default:
        return { success: false, message: `未知 action: ${action}` }
    }
  } catch (error) {
    console.error('[manageDailyPicks] 错误:', error)
    return { success: false, message: error.message || '操作失败' }
  }
})

/**
 * 获取指定日期的精选资源
 */
async function getPicksByDate(event) {
  const { date } = event
  if (!date) {
    return { success: false, message: '缺少 date 参数（格式 YYYY-MM-DD）' }
  }

  const res = await db.collection('daily_picks')
    .where({ date })
    .limit(1)
    .get()

  if (res.data.length === 0) {
    return { success: true, data: { date, resources: [], autoGenerated: false } }
  }

  const pickDoc = res.data[0]
  const resourceIds = pickDoc.resourceIds || []

  // 批量查询资源详情
  let resources = []
  if (resourceIds.length > 0) {
    for (let i = 0; i < resourceIds.length; i += 20) {
      const batch = resourceIds.slice(i, i + 20)
      const resBatch = await db.collection('resources')
        .where({ _id: _.in(batch), deletedAt: null })
        .field({ _id: true, title: true, coverUrl: true, url: true, type: true, status: true, tags: true })
        .get()
        .catch(() => ({ data: [] }))
      resources = resources.concat(resBatch.data)
    }
  }

  return {
    success: true,
    data: {
      date,
      resources,
      autoGenerated: !!pickDoc.autoGenerated,
      updatedAt: pickDoc.updatedAt || null
    }
  }
}

/**
 * 设置某天的精选资源（覆盖写入）
 */
async function setPicks(event, admin) {
  const { date, resourceIds } = event

  if (!date) {
    return { success: false, message: '缺少 date 参数' }
  }
  if (!Array.isArray(resourceIds)) {
    return { success: false, message: 'resourceIds 必须为数组' }
  }

  const existing = await db.collection('daily_picks')
    .where({ date })
    .limit(1)
    .get()

  const pickData = {
    date,
    resourceIds,
    autoGenerated: false,
    operatedBy: admin?.username || 'admin',
    updatedAt: new Date()
  }

  if (existing.data.length > 0) {
    await db.collection('daily_picks').doc(existing.data[0]._id).update({ data: pickData })
  } else {
    pickData.createdAt = new Date()
    await db.collection('daily_picks').add({ data: pickData })
  }

  return { success: true, message: `${date} 精选已更新，共 ${resourceIds.length} 项` }
}

/**
 * 移除某天的某项资源
 */
async function removePick(event) {
  const { date, resourceId } = event
  if (!date || !resourceId) {
    return { success: false, message: '缺少 date 或 resourceId' }
  }

  const existing = await db.collection('daily_picks')
    .where({ date })
    .limit(1)
    .get()

  if (existing.data.length === 0) {
    return { success: false, message: '该日期无精选配置' }
  }

  const doc = existing.data[0]
  const newIds = (doc.resourceIds || []).filter(id => id !== resourceId)

  await db.collection('daily_picks').doc(doc._id).update({
    data: { resourceIds: newIds, updatedAt: new Date() }
  })

  return { success: true, message: '已移除', remaining: newIds.length }
}

/**
 * 批量获取日期范围内的精选配置
 */
async function getPicksRange(event) {
  const { startDate, endDate } = event
  if (!startDate || !endDate) {
    return { success: false, message: '缺少 startDate 或 endDate' }
  }

  const res = await db.collection('daily_picks')
    .where({
      date: _.gte(startDate).and(_.lte(endDate))
    })
    .orderBy('date', 'asc')
    .limit(100)
    .get()

  return {
    success: true,
    data: res.data.map(d => ({
      date: d.date,
      count: (d.resourceIds || []).length,
      autoGenerated: !!d.autoGenerated,
      updatedAt: d.updatedAt || null
    }))
  }
}

/**
 * 获取自动精选开关配置
 */
async function getAutoConfig() {
  const res = await db.collection('config')
    .where({ key: 'daily_picks_auto' })
    .limit(1)
    .get()

  if (res.data.length > 0) {
    return { success: true, data: res.data[0].value }
  }
  return { success: true, data: { enabled: true, minCount: 6, maxCount: 12 } }
}

/**
 * 更新自动精选开关配置
 */
async function updateAutoConfig(event) {
  const { data } = event
  if (!data || typeof data !== 'object') {
    return { success: false, message: '缺少配置数据' }
  }

  const existing = await db.collection('config')
    .where({ key: 'daily_picks_auto' })
    .limit(1)
    .get()

  const value = {
    enabled: data.enabled !== false,
    minCount: data.minCount || 6,
    maxCount: data.maxCount || 12,
    updatedAt: new Date()
  }

  if (existing.data.length > 0) {
    await db.collection('config').doc(existing.data[0]._id).update({
      data: { value, updatedAt: db.serverDate() }
    })
  } else {
    await db.collection('config').add({
      data: { key: 'daily_picks_auto', value, createdAt: db.serverDate() }
    })
  }

  return { success: true, message: '自动精选配置已更新' }
}
